# Script to generate all remaining dashboard files from templates
# This creates posted-packages and place-booking pages for all vendor dashboards

$dashboardConfigs = @(
    @{
        name = "fashion-beauty"
        org = "Glamour Beauty Studio"
        initial = "G"
        service = "fashion & beauty"
        storageKey = "fashionBeautyPackages"
        bookingKey = "fashionBeautyBookings"
        categoryType = "BeautyCategory"
        categories = @("bridal-makeup", "hair-styling", "traditional-dressing")
        categoryLabels = @("Bridal Makeup", "Hair Styling", "Traditional Dressing")
        bannerTexts = @("Bridal Makeup Packages", "Hair Styling Packages", "Traditional Dressing Packages")
        bookingTexts = @("Bridal Makeup Bookings", "Hair Styling Bookings", "Traditional Dressing Bookings")
    },
    @{
        name = "entertainment"
        org = "Entertainment Plus"
        initial = "E"
        service = "entertainment"
        storageKey = "entertainmentPackages"
        bookingKey = "entertainmentBookings"
        categoryType = "EntertainmentCategory"
        categories = @("live-bands", "djs", "traditional-performers")
        categoryLabels = @("Live Bands", "DJs", "Traditional Performers")
        bannerTexts = @("Live Bands Packages", "DJ Packages", "Traditional Performers Packages")
        bookingTexts = @("Live Bands Bookings", "DJ Bookings", "Traditional Performers Bookings")
    },
    @{
        name = "transportation"
        org = "Elite Transport"
        initial = "T"
        service = "transportation"
        storageKey = "transportationPackages"
        bookingKey = "transportationBookings"
        categoryType = "TransportCategory"
        categories = @("wedding-cars", "luxury-vehicles", "guest-transport")
        categoryLabels = @("Wedding Cars", "Luxury Vehicles", "Guest Transport")
        bannerTexts = @("Wedding Cars Packages", "Luxury Vehicles Packages", "Guest Transport Packages")
        bookingTexts = @("Wedding Cars Bookings", "Luxury Vehicles Bookings", "Guest Transport Bookings")
    },
    @{
        name = "ceremonial"
        org = "Sacred Ceremonies"
        initial = "S"
        service = "ceremonial services"
        storageKey = "ceremonialPackages"
        bookingKey = "ceremonialBookings"
        categoryType = "CeremonialCategory"
        categories = @("poruwa-ceremony", "religious-services", "cultural-events")
        categoryLabels = @("Poruwa Ceremony", "Religious Services", "Cultural Events")
        bannerTexts = @("Poruwa Ceremony Packages", "Religious Services Packages", "Cultural Events Packages")
        bookingTexts = @("Poruwa Ceremony Bookings", "Religious Services Bookings", "Cultural Events Bookings")
    },
    @{
        name = "cake-decoration"
        org = "Sweet Celebrations"
        initial = "C"
        service = "cake decoration"
        storageKey = "cakePackages"
        bookingKey = "cakeBookings"
        categoryType = "CakeCategory"
        categories = @("wedding-cakes", "tiered-cakes", "custom-designs")
        categoryLabels = @("Wedding Cakes", "Tiered Cakes", "Custom Designs")
        bannerTexts = @("Wedding Cakes Packages", "Tiered Cakes Packages", "Custom Designs Packages")
        bookingTexts = @("Wedding Cakes Bookings", "Tiered Cakes Bookings", "Custom Designs Bookings")
    },
    @{
        name = "gifting"
        org = "Memorable Gifts"
        initial = "M"
        service = "gifting & souvenirs"
        storageKey = "giftingPackages"
        bookingKey = "giftingBookings"
        categoryType = "GiftingCategory"
        categories = @("wedding-favors", "gift-boxes", "custom-souvenirs")
        categoryLabels = @("Wedding Favors", "Gift Boxes", "Custom Souvenirs")
        bannerTexts = @("Wedding Favors Packages", "Gift Boxes Packages", "Custom Souvenirs Packages")
        bookingTexts = @("Wedding Favors Bookings", "Gift Boxes Bookings", "Custom Souvenirs Bookings")
    }
)

Write-Host "============================================" -ForegroundColor Cyan
Write-Host "Dashboard File Generator - Configuration Ready" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "This script contains configurations for:" -ForegroundColor Green
foreach ($config in $dashboardConfigs) {
    Write-Host "  ✓ $($config.org) ($($config.name))" -ForegroundColor Yellow
    Write-Host "    Categories: $($config.categoryLabels -join ', ')" -ForegroundColor Gray
}
Write-Host ""
Write-Host "Files will be generated by the AI assistant using these configurations." -ForegroundColor Cyan
Write-Host "Total files to create: $($dashboardConfigs.Count * 2) files" -ForegroundColor Green

# Export configuration for use by AI
$global:DashboardConfigs = $dashboardConfigs
Write-Host "`nConfiguration loaded into `$global:DashboardConfigs" -ForegroundColor Green
