import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import CryptoRandomUUIDPolyfill from '@/components/CryptoRandomUUIDPolyfill';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const seasonFont = Playfair_Display({
  variable: "--font-season",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${seasonFont.variable} antialiased`}
        suppressHydrationWarning
      >
        <CryptoRandomUUIDPolyfill />
        {children}
      </body>
    </html>
  );
}
